server:
  port: 8080
  session.timeout: 0

spring:
  datasource:
    driverClassName: org.h2.Driver
    platform: h2
    url: "jdbc:h2:~/carpooling;AUTO_SERVER=TRUE;MODE=PostgreSQL;"
    username: sa
    password:
  jpa:
    database: H2
    generate-ddl: true
    hibernate.ddl-auto: create-drop