server:
  port: 8080
  session.timeout: 0

spring:
  datasource:
    driverClassName: org.h2.Driver
    platform: h2
    url: "jdbc:h2:~/carpooling;AUTO_SERVER=TRUE;MODE=PostgreSQL;"
    username: sa
    password:

file:
  upload:
    images:
      path: src/main/resources/public/images
      avatars:
        path: ${file.upload.images.path}/avatars/
        thumbnail:
          path: ${file.upload.images.avatars.path}/thumbs/
        maxLongSide: 150

logging:
  level:
    pl.lodz.p.carpooling: DEBUG