server:
  port: 8080
  session.timeout: 0

spring:
  datasource:
    driverClassName: org.h2.Driver
    platform: h2
    url: "jdbc:h2:~/carpooling;AUTO_SERVER=TRUE;MODE=PostgreSQL;"
    username: sa
    password:

logging:
  level:
    pl.lodz.p.carpooling: DEBUG